services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - agronetwork

networks:
  agronetwork:
    external: true
